### ISSUE TITLE
API for user login to application

### ISSUE THREAD

**Issue by satabdisikdar** [splitwise/api-docs#16]
Where can I get the API for user login? I don't see that in API documentation https://dev.splitwise.com/

**Comment by rofreg** [comment]
Hey there – apologies for the slow reply! You'll want to follow the instructions in the [Authentication](https://dev.splitwise.com/#authentication) section of our API docs.

The Splitwise API uses a standard OAuth flow for user login, which goes something like this:

- Your app uses your consumer key and consumer secret to construct an "authorization URL". This authorization URL points to a page on splitwise.com.
- Next, the user goes to this URL. On this page, they can log in to their Splitwise account (if they're not already logged in) and grant permission to your application to access their data.
- If the user grants permission, then Splitwise redirects back to your app with data about the logged-in user. The credentials included in this data allow you to make subsequent API requests as that user.

Note that the Splitwise API does not let you log in directly – you cannot directly pass a user's email address and password to the Splitwise API. The OAuth authentication flow was designed to let a user securely log in and grant access to your app, without the user ever needing to tell your app their Splitwise user credentials.
