### ISSUE TITLE
documentation missing for many API Methods

### ISSUE THREAD

**Issue by goleary** [splitwise/api-docs#19]
Many of the methods seem to be entirely missing any documentation/examples:
![image](https://user-images.githubusercontent.com/16123225/68905318-a4ceec80-06f5-11ea-852c-7b7f323306ba.png)
http://dev.splitwise.com/?javascript#create_expense

**Comment by rofreg** [comment]
Sorry for the confusion! It's easy to miss, but there's a link to our [legacy API docs](http://dev.legacy.splitwise.com/) near the top of our new API docs, with a note that the new docs are still a work in progress. We hope to finish filling out the rest of our new API site soon!

**Comment by goleary** [comment]
i see, thanks!
