### ISSUE TITLE
Is it possible to upload a receipt picture using the API?

### ISSUE THREAD

**Issue by SimplyNaOH** [splitwise/api-docs#21]
What the title says: both on the web-app and the mobile-app it is possible to attach a picture to an expense, is this functionality exposed  in the API? I am trying  to write some scripts for personal use to automatize entry of expenses and it would be nice if I can do it all in one place.. otherwise I would need to go back into the app and update the generated expenses to add the pictures...

**Comment by jas14** [comment]
Yes, just include a `receipt` parameter to `create_expense`. The value should be the file you want to upload. You will need to use the `multipart/form-data` content disposition for this to work properly.

Hope this helps!
