### ISSUE TITLE
create_expense for a group

### ISSUE THREAD

**Issue by goleary** [splitwise/api-docs#25]
I'd like to use the create_expense endpoint to submit an expense for a group and have it split amongst all members.  Does the splitwise API provide this functionality?

I'm really hoping I don't have to pull a list of all group members and then do all of the math on my end and then submit the expense in a separate request.

When I submit an expense with `group_id` populated, but no user I get an error...

**Comment by goleary** [comment]
I see. This is exactly what I was looking for, thanks!

That said, due to the lack of documentation perhaps this issue should remain open until this information is available self serve?

I'd be happy to help contribute to the docs, but considering the lack of any details in the (new) expense section, I'm a bit hesitant.  It seems like someone on your end should get it started.

:)

**Comment by pokekey** [comment]
Thanks for the notes here.  Helped me successfully implement create_expense

**Comment by jas14** [comment]
The docs have been updated: https://dev.splitwise.com/#create_expense

**Comment by goleary** [comment]
unreal, thanks Joe! They look great.

**Comment by jas14** [comment]
Thanks go to @mgod for #32! 🙂
