### ISSUE TITLE
Documentation Mistake: for api get_friend/:id

### ISSUE THREAD

**Issue by APatil010** [splitwise/api-docs#27]
While going through the docs, the specific endpoint  "get_friend/:id" has wrong path in the API.
It is given to be,

**GET https://secure.splitwise.com/api/v3.0/get_group/:id**
**Get detailed info on one group that current_user belongs to**

Whereas the path & documentation should be changed,

**GET https://secure.splitwise.com/api/v3.0/get_friend/:id**
**Get detailed info on one friend that current_user has**

Just wanted the next person reading the docs not face this simple mistake.
Thanks

**Comment by jas14** [comment]
Good catch @APatil010 , thanks for letting us know!
