### ISSUE TITLE
CORS error when calling api from javascript

### ISSUE THREAD

**Issue by davidnoorda** [splitwise/api-docs#30]
Hello,

I'm hoping to write a client side app but it seems like it won't work?

I am able to authenticate okay but I am getting the following error when calling the api:

> Access to fetch at 'https://secure.splitwise.com/api/v3.0/get_current_user' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Is this a security measure on your end? Is there some way to get around it or will I need server code?

Here is my calling code:
```javascript
function getCurrentUser(accessToken) {
  let url = "https://secure.splitwise.com/api/v3.0/get_current_user";
  let auth = "Bearer " + accessToken;

  var myHeaders = new Headers();
  myHeaders.append("Authorization", auth);

  var requestOptions = {
    method: "GET",
    headers: myHeaders,
    redirect: "follow",
  };

  fetch(url, requestOptions)
    .then((response) => response.json())
    .then((result) => console.log(result))
    .catch((error) => console.log("error", error));
}
```

**Comment by jas14** [comment]
Hi @davidnoorda , thanks for the writeup. Unfortunately, we don't support JavaScript browser API clients at this time, so yes, you will need another platform (e.g. server) for your client. Sorry for the inconvenience!

**Comment by davidnoorda** [comment]
Hi @jas14, no worries, thanks for the quick reply!
