### ISSUE TITLE
React Native Integration

### ISSUE THREAD

**Issue by adityasamant** [splitwise/api-docs#42]
I am developing a react native app. Is there a way to use Splitwise API on the app? 
Integration with Splitwise is one of the crucial functionalities of my app.
Thanks in advance.

**Comment by jas14** [comment]
@adityasamant we don't provide a React Native SDK if that's what you're asking, but there is a community-written [JS SDK](https://github.com/keriwarr/splitwise) that you may find helpful, and you can always use the API directly - please see [the docs](https://dev.splitwise.com).
