### ISSUE TITLE
Getting 404 when requesting token of oauth2

### ISSUE THREAD

**Issue by Enterisr** [splitwise/api-docs#43]
Hey there!
Recently I've tried to make a request for the 'https://secure.splitwise.com/oauth/token' endpoint (after the callback_uri called successfully of course)  , but it seemed down from some reason and **returns 404**. 

Maybe the problem is with the request, But I tried to copy exactly the standard token request format to no help. 

May you please take a look at that?  
I am appending the fetch request so you'll see what I'm doing.
![image](https://user-images.githubusercontent.com/11784580/103430480-2ff69480-4bcd-11eb-8bbc-52c6573196e9.png)
Thank you and happy new year!

**Comment by jas14** [comment]
@Enterisr I see you're trying to submit your client ID and secret as part of an `Authorization: Basic` header. We're expecting your OAuth client ID and secret to be passed as parameters, namely `client_id` and `client_secret`, not as a header. Happy new year!

**Comment by Enterisr** [comment]
Thank you for you help, I really appreciate it! 
Sadly now I'm getting 400 with "unsupported_grant_type". Tried to add the contentType header, but nothing came through besides 400.

**Comment by jas14** [comment]
@Enterisr you're quite welcome! I'm afraid it'll be quite difficult to debug your specific case, but make sure `grant_type` is `authorization_code`.

**Comment by aschoerg** [comment]
Hi @jas14, hi @Enterisr,

Nice to see that the issues are answered! :+1: I am facing a very similar issue and I really would need your help :)

When I send a POST to :
```
https://www.splitwise.com/oauth/token
?code=<obtained code>
&grant_type=authorization_code
&client_id=<splitwise_consumer_key>
&client_secret=<splitwise_consumer_secret>
&redirect_uri=http://localhost
```

I don't get unsupported_grant_type, but:
```json
{
    "error": "invalid_grant"
}
```

I dug into it a little more, using the JS-example provided http://dev.splitwise.com/?javascript#authentication ...

```js
client.getOAuthAccessToken(
      qsObj.code,
      {
        'redirect_uri': MY_CALLBACK_URL,
        'grant_type': 'authorization_code'
      },
      function(e, access_token, refresh_token, results) {...}
)
```

... and looking at the source code from node-oauth library https://github.com/ciaranj/node-oauth/blob/master/lib/oauth2.js#L177-L190 translates to a params object of
```js
params['redirect_uri'] = MY_CALLBACK_URL;
params['grant_type'] = 'authorization_code';
params['client_id'] = this._clientId;
params['client_secret'] = this._client_secret;
params['code'] = code;
```

This is then POSTed as `application/x-www-form-urlencoded` to `https://www.splitwise.com/oauth/token`.

And when I use PostMan to send the queryparams as headers:
![image](https://user-images.githubusercontent.com/6042536/103913227-a08b3d00-5108-11eb-8358-656b3664c60a.png)

I get `400 Bad Request`, some session cookies from splitwise.com, and the same:
```json
{
    "error": "invalid_grant"
}
```

@jas14, please illuminate us, **What do we need to send?**

Thank you in advance,
Happy new Year,
Alex

**Comment by aschoerg** [comment]
@Enterisr I am not sure if this helps you, but it seems you are sending grant_type and the code in the body instead of form-urlencoded?

**Comment by aschoerg** [comment]
OMG I solved it! Stupid mistake, I am going to edit this comment

**Comment by aschoerg** [comment]
@Enterisr 

Make sure to send the parameters as described in the above format. I tried the following in JS/node:

```js
const fetch = require("node-fetch");

async function fetchToken() {
  let formBody = 
	  ["code=<obtained code>",
	  "grant_type=authorization_code",
	  "client_id=<splitwise_consumer_key>",
	  "client_secret=<splitwise_consumer_secret>",
	  "redirect_uri=<callback_url>"
	  ];
  let headers = "Content-Type:application/x-www-form-urlencoded";
  fetch('https://secure.splitwise.com/oauth/token', {
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: formBody.join("&"),
    mode: 'cors',
    method: 'POST'
  }).then(r => r.json()).then(ret => console.log(ret)).catch(e => console.log(e));

}

fetchToken();
```

Good Luck! :four_leaf_clover:

**Comment by Enterisr** [comment]
@aschoerg Thank you for reaching out. Your answser did help me to get to 200. 
I will attach here key notes that was not clear to me beforehand: 

1.**The body should not be sent in json format, but in a "query like" format - x-www-form-urlencoded**
2.The redirect_uri should be the same uri that you given to the 'https://secure.splitwise.com/oauth/authorize' request, and that you entered in the site. 

@jas14 
Thank you for your help! 
Maybe it will be a good idea to allow developers more than one callback url, like you have in the spotify api 🤔. But this is off-topic, so I will close this issue.

Thank you again!
