### ISSUE TITLE
authorization url does not have code parameter

### ISSUE THREAD

**Issue by c-14795** [splitwise/api-docs#54]
When tried to fetch the oauth2 code from the splitwise python sdk, using **getOAuth2AuthorizeURL** , code part is missing from url.
 see below.
https://www.splitwise.com/oauth/authorize?response_type=code&client_id=<client_id>&redirect_uri=<callback_url>&state=<state>

**Comment by jas14** [comment]
Hey there, the user authorization step of the [OAuth2 authorization code flow](https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type) isn't supposed to have an authorization code in the URL. That's included in the callback immediately after authorization. Can you describe what you were you expecting to see?

**Comment by c-14795** [comment]
Hello,  my callback url is  https://www.sumanraju.com/,  after hitting the above url, it is requesting for approval, once approved, it  directly goes to splitwise home page,

**Comment by jas14** [comment]
Did you register your callback URL with Splitwise when creating the app? If not, you'll need to go back and supply it.

**Comment by c-14795** [comment]
yes I did.

**Comment by jas14** [comment]
I see some log lines with the redirect URI you provided above, but the corresponding application does not have a callback URL registered.

Note that this is different from the _homepage_ URL, which is for human-readable information about your app, not programmatic authorization.

<img width="357" alt="Screen Shot 2022-02-03 at 8 01 28 AM" src="https://user-images.githubusercontent.com/569991/152347933-d87a8498-95a1-45a0-b5db-c24ea0a6b22b.png">

**Comment by rofreg** [comment]
I'm going to mark this issue as closed, as we believe the API docs and the API itself are both working as intended. If you have more issues or questions, feel free to reach out to [developers@splitwise.com](mailto:developers@splitwise.com)!
