### ISSUE TITLE
How can I create an expense split equally between a subset of the group?

### ISSUE THREAD

**Issue by fmilani** [splitwise/api-docs#59]
I see in the docs that I can create an expense with a group_id and the flag split_equally set to true to split equally between all members of that group, but I want to split equally between only some members of the group, without having to use the "by_shares" version. How can I do that?

Thanks in advance!

**Comment by jas14** [comment]
Hi @fmilani , thanks for writing in! We don't currently support what you're describing; you'll unfortunately have to do the math yourself for anything more complicated than an equal split between all members of a group.

**Comment by fmilani** [comment]
Got it. Thanks for the reply!
