### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by nobrains** [splitwise/api-docs#6]
Hey Team, I used the exact same code as mentioned at dev.beta.splitwise.com. From my local machine  the user is getting directed to splitwise, he is asked for permission, but once he clicks on Authorize, he is taken to the splitwise website instead of being redirected back to the "redirect_uri".

<img width="860" alt="screen shot 2018-07-29 at 1 11 31 pm" src="https://user-images.githubusercontent.com/151825/43364084-ff0686e8-9330-11e8-8725-b97629fe904a.png">

**Comment by mgod** [comment]
When you created your OAuth application in Splitwise, did you set `http://localhost/callback as the redirect there? OAuth will not allow you to specify an arbitrary redirect url, it needs to match characteristics of the redirect allowed with your initial client application configuration, and an exact match is the easiest for make sure is correct.
