### ISSUE TITLE
Simple API tokens

### ISSUE THREAD

**Issue by juanedi** [splitwise/api-docs#8]
This isn't really an issue with the current API for more of a request.

It would be great if we were able to create API tokens from our account settings to make it easier to start using the API.

I mean something like what Github provides in `https://github.com/settings/tokens`.

That way one could test out ideas or build whole integrations not intended for general use without going through the OAuth setup flow.

Is that reasonable? Thanks!

**Comment by rofreg** [comment]
I like this suggestion a lot! I'll add this to our list of possible improvements, as I can see how it would make it a lot easier to get started with development or to develop simple one-off integrations.

**Comment by jas14** [comment]
We've just enabled per-app API keys to improve ease of development. While you must still register an app, you can now generate a key tied to your account on your app's detail page! I'll close this issue once this is documented.

**Comment by juanedi** [comment]
That's awesome. Thank you!
