### ISSUE TITLE
[Github Actions Bug?] Loooooong Running CI :D 

### ISSUE THREAD

**Issue by scott-hannan** [splitwise/api-docs#87]
Hey!

This is definitely not a traditional issue, I was just poking around the repo and noticed there was an action that is running, and that has been running for almost 2 months. I am not sure if this is just a GHA bug. But, knowing how GHA bills minutes I thought I'd just flag it just in case its not :D 

The action run: https://github.com/splitwise/api-docs/actions/runs/8378974745/job/22944811104 

If this is just a bug, and I am making this issue for nothing, please let me know and I will close this straight away

![image](https://github.com/splitwise/api-docs/assets/117687334/39e9da61-d6ef-4540-bf85-719bbb6fc77c)

**Comment by scott-hannan** [comment]
GHA Bug

**Comment by jas14** [comment]
Thanks for flagging!
